-- Migração: substituir solicitantes pelos padrões do CSV
-- Rodar: npm run db:migrate -- replace-solicitantes
-- Fonte: production/initial-data/solicitantes.csv

DELETE FROM solicitantes;

INSERT INTO solicitantes (id, nome, "unResponsavel") VALUES
  ('sol-001', 'Thalyta', '—'),
  ('sol-002', 'Coutinho', '—'),
  ('sol-003', 'Laysa Gomes', '—'),
  ('sol-004', 'Denise Brasileiro', '—'),
  ('sol-005', 'Paulo Emílio Alves Ribeiro', '—'),
  ('sol-006', 'Carol Campos', '—'),
  ('sol-007', 'UN Açailândia', '—'),
  ('sol-008', 'Erika', '—'),
  ('sol-009', 'Luis (UNE)', '—'),
  ('sol-010', 'Raunyr', '—'),
  ('sol-011', 'UN Balsas', '—'),
  ('sol-012', 'SLP EVENTOS', '—'),
  ('sol-013', 'Valquíria', '—'),
  ('sol-014', 'UCOM', '—'),
  ('sol-015', 'Rejane Lamarka', '—'),
  ('sol-016', 'Luciana (Soluções)', '—'),
  ('sol-017', 'William Morais', '—'),
  ('sol-018', 'Nicia', '—'),
  ('sol-019', 'Cynthia', '—'),
  ('sol-020', 'Tiago', '—'),
  ('sol-021', 'Raissa Kaline', '—'),
  ('sol-022', 'CDE', '—'),
  ('sol-023', 'UN Caxias', '—'),
  ('sol-024', 'UN Lençóis Munim', '—'),
  ('sol-025', 'UPCO', '—'),
  ('sol-026', 'UGE', '—'),
  ('sol-027', 'UAN', '—'),
  ('sol-028', 'UN São Luís', '—'),
  ('sol-029', 'Multicenter', '—'),
  ('sol-030', 'Igor Almeida', '—'),
  ('sol-031', 'Contratos Partners', '—'),
  ('sol-032', 'Geisa Almeida', '—'),
  ('sol-033', 'Juliana Oliveira', '—'),
  ('sol-034', 'Tatiana', '—'),
  ('sol-035', 'Felipe Ladeira', '—'),
  ('sol-036', 'Und Imperatriz', '—'),
  ('sol-037', 'UN Bacabal', '—'),
  ('sol-038', 'Gabriel Lima', '—'),
  ('sol-039', 'Flamilla Costa', '—'),
  ('sol-040', 'Pablo Lemos', '—'),
  ('sol-041', 'Jacqueline', '—'),
  ('sol-042', 'Un Santa Inês', '—'),
  ('sol-043', 'Lorenna (Chapadinha)', '—'),
  ('sol-044', 'Ydiara', '—'),
  ('sol-045', 'UN Pinheiro', '—'),
  ('sol-046', 'Jorge (Grajaú)', '—'),
  ('sol-047', 'UET Sebrae', '—'),
  ('sol-048', 'Atendimento', '—'),
  ('sol-049', 'Fábio Braga', '—'),
  ('sol-050', 'Dóris', '—'),
  ('sol-051', 'Ana Carla', '—'),
  ('sol-052', 'Sara', '—'),
  ('sol-053', 'Mauro (Balsas)', '—'),
  ('sol-054', 'Graziele', '—'),
  ('sol-055', 'Cassio', '—'),
  ('sol-056', 'Amparo', '—'),
  ('sol-057', 'Jhon', '—'),
  ('sol-058', 'Evandro', '—'),
  ('sol-059', 'Milena', '—'),
  ('sol-060', 'Brenda Lima', '—'),
  ('sol-061', 'Hildene Maia', '—'),
  ('sol-062', 'Jaime Coelho', '—'),
  ('sol-063', 'César Augusto', '—'),
  ('sol-064', 'José Noleto', '—'),
  ('sol-065', 'Antônio Marão', '—'),
  ('sol-066', 'Tania Gardenia', '—'),
  ('sol-067', 'Marco Aurélio', '—'),
  ('sol-068', 'Anna Caroline', '—'),
  ('sol-069', 'Maurício Leite', '—'),
  ('sol-070', 'Allan Kenedy', '—'),
  ('sol-071', 'Gallion Filmes', '—'),
  ('sol-072', 'Arthur Henrique Couto Polary', '—'),
  ('sol-073', 'G H Eventos Comercial', '—'),
  ('sol-074', 'Equipar Eventos', '—'),
  ('sol-075', 'Ideia Interativa', '—'),
  ('sol-076', 'Camila Bastos', '—'),
  ('sol-077', 'Alcides Barbosa', '—'),
  ('sol-078', 'Rosaline Dourado', '—'),
  ('sol-079', 'Rafael Lima', '—'),
  ('sol-080', 'Dayse Castro', '—'),
  ('sol-081', 'Ruid Oliveira', '—'),
  ('sol-082', 'Camilla', '—'),
  ('sol-083', 'João Torres', '—'),
  ('sol-084', 'Suzana Cunha', '—'),
  ('sol-085', 'Grazielle', '—'),
  ('sol-086', 'Lila Antoniere', '—'),
  ('sol-087', 'Cris Gonçalves', '—'),
  ('sol-088', 'Jordana Fonseca', '—'),
  ('sol-089', 'Henrique Coutinho', '—'),
  ('sol-090', 'Mayna', '—'),
  ('sol-091', 'Rossane Goes', '—'),
  ('sol-092', 'Laurene', '—'),
  ('sol-093', 'Lorena', '—'),
  ('sol-094', 'Letícia Gusmão', '—');
